name: "Build Project"
on:
  push:
    branches:
      - '**'

jobs:
  build:
    uses: ./.github/workflows/generic_build.yml
  upload_artifact:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@4
      - name: "Build Project"
        uses: ./.github/workflows/generic_build.yml
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v7
        with:
          path: .
