name: "Build Project"
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build Project"
        uses: ./.github/workflows/generic_build.yml
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v7
        with:
          path: .
